// Auto generated by solid-file-router
/* prettier-ignore */
/* eslint-disable */

export {}

declare module 'solid-file-router' {
  interface FileRoutePath {
    '/': never
    '/base64': never
    '/converter': never
    '/data': never
    '/formatter': never
    '/key-converter': never
    '/uuid': never
  }
  interface FileRouteInfo {
    title: string
    description: string
    category: string
    icon: string
    tags: string[]
  }
}
