// Auto generated by solid-file-router
/* eslint-disable */

export {}

declare module 'solid-file-router' {
  namespace FileRouteInfo {
    interface Path {
      '/': never
      '/base64': never
      '/converter': never
      '/data': never
      '/formatter': never
      '/key-converter': never
      '/uuid': never
    }
  }
}
